### PR TITLE
Small updates

### PR DESCRIPTION
**Pull request by hmcty**
We're about to have some increased traffic with the upcoming John Deere event, so I figured we should update the project website pages. To enable this I made some changes that were requested by Raghava in his project pull request and changes the navigation to include the members page. Let me know what you think.

### CODE REVIEW

**Comment by hmcty** [comment]
How come we are ditching old members? I think it would be cool to track, we just need to fix the display issue.

**Comment by jrbaxter0** [comment]
> 
> 
> How come we are ditching old members? I think it would be cool to track, we just need to fix the display issue.

good point. Reverted.

It bothers me that the timestamps are wrong, but idk how to fix them. WSL2 clock was off by 2 days :(

**Comment by hmcty** [comment]
Which timestamps are wrong?

I also checked my branch with the Robot Arm update locally and everything seemed to look fine. So as soon as we merge this one in, we can also merge that.

**Comment by jrbaxter0** [comment]
> 
> Which timestamps are wrong?
> 

my commits show as earlier than yours since my clock was off

**Pull request merged**
