### PR TITLE
Updated to new website

### PR DESCRIPTION
**Pull request by raghavauppuluri13**

### CODE REVIEW

**Comment by raghavauppuluri13** [comment]
@hmccarty Let me know if this looks good. Want to ensure things are looking clean sooner than later so we can catch things quicker. Directions for running things are in the readme, and are simpler than jekyll.

**Comment by hmcty** [comment]
Made some changes, load it locally and lmk what you think. If there's anything you don't agree with, we can roll-back commits.

Few things left to do (leaving here for mental note):

- Integrate typeform with Discord
- Small UI tweaks (discord and GCal styling, padding of some content)
- Updating of articles (remove example ones, fix new fall one, add important additional articles)
- Fix member page

Potential articles we may want:
- About us: more verbose description of the club and our history
- Project breakdown? (Updated list of ongoing projects and a few sentences about their status)

**Comment by hmcty** [comment]
Another quick thought: may be nice to optionally decide whether to include the teaser image in blog post. Like callout post could be fine with a pure textual layout.

**Comment by raghavauppuluri13** [comment]
Might be possible if you remove the hero param in the article. Not totally sure though.

**Comment by raghavauppuluri13** [comment]
See if you can make those bullets into issues. If that's all we need to change, I can start banging some those out this weekend and Monday. When should we plan to deploy?

**Comment by hmcty** [comment]
Gonna target a few of these points right now, so issues for all may not be necessary. Let's see how far I get.

As far as deploying, Monday seems appropriate as it's a week before school starts.

**Comment by hmcty** [comment]
List update:
- ~~Integrate typeform with Discord~~
- Small UI tweaks (discord and GCal styling, padding of some content)
- ~~Updating of articles (remove example ones, fix new fall one, add important additional articles)~~
- Fix member page
- ~~About us: more verbose description of the club and our history~~

Think this is good enough for launch. I'll open the other two as issues.

**Review by hmcty — APPROVED** [review]

**Pull request merged**
